# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - '7.0'
  - '7.3'

env:
  global:
    - TARGET_COMMIT=$([[ -z ${TRAVIS_PULL_REQUEST_SHA} ]] && git merge-base HEAD origin/master || echo ${TRAVIS_PULL_REQUEST_SHA})
  matrix:
    - COMPOSER_PARAMETER=--prefer-lowest
    - COMPOSER_PARAMETER=

matrix:
  fast_finish: true

before_install:
  - nvm install v10.19.0
  - nvm alias default v10.19.0
  - travis_retry composer self-update --1
  - travis_retry composer config -g github-oauth.github.com $GH_TOKEN
  - composer validate -n
  - >
    if [[ ${TRAVIS_PHP_VERSION} != '7.0' ]]; then
      composer global require --no-progress infection/infection;
    fi

install:
  - travis_retry composer update -n --no-progress --no-suggest $COMPOSER_PARAMETER
  - composer show -i

script:
  - composer validate -n
  - src/bin/coding-standard sca:all -t $TARGET_COMMIT
  - php vendor/bin/phpunit --config phpunit.xml
  - >
    if [[ ${TRAVIS_PHP_VERSION} != '7.0' && ${COMPOSER_PARAMETER} != '--prefer-lowest' ]]; then
      $(composer config --global home)/$(composer config --global bin-dir)/infection --min-msi=78 --min-covered-msi=80 --threads=4
    fi

# allow builds for all branches
branches:
  only:
    - /.*/

# disable shallow cloning
git:
  depth: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
