# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.6
  - 7.0
  - nightly

# optionally set up exclutions and allowed failures in the matrix
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer config -g github-oauth.github.com $GH_TOKEN
  - travis_retry composer install

script:
  - src/bin/coding-standard all -t $TRAVIS_BRANCH
  - php vendor/bin/phpunit --config phpunit.xml

# allow builds for all branches
branches:
  only:
    - /.*/

# disable shallow cloning
git:
  depth: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
